- src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
- success handler의 리다이렉트 url 수정
-
> fix: localhost를 서비스 도메인으로 변경

- src/main/java/com/strcat/service/OAuthUserService.java
유저가 있으면 회원가입이 되도록 잘못 지정되었던 분기문을 수정
- OAuthUserService 분기문 오류 수정
-
> fix: OAuthUserService 분기문 오류 수정

- src/main/java/com/strcat/config/SecurityConfig.java
- src/main/java/com/strcat/config/WebConfig.java
- CORS 설정을 위해 WebCofig 설정
- 테스트를 위해 모든 origin allow함
- GET, POST에 대해 allow함
- #9
> feat: CORS 설정을 위한 WebCofig 추가 #9

- build.gradle
- src/main/java/com/strcat/config/SecurityConfig.java
- src/main/java/com/strcat/domain/OAuthUser.java
- src/main/java/com/strcat/domain/User.java
- src/main/java/com/strcat/service/OAuthUserService.java
- @Data, @NoArgsConstructor로 Getter, Setter 메소드 대체
- @Slf4j로 로그 메세지 대체
- #12
> [Feat] lombok 적용을 위한 기존 코드 수정 #12

- src/main/java/com/strcat/config/SecurityConfig.java
- src/main/java/com/strcat/service/OAuthUserService.java
- git conflict 잘못 수정해서 병합한 부분 수정
-
> [Fix] git conflict 수정

- .gitmodules
- 서브모듈 추가 및 .properties 파일 추가
-
> [Chore] 서브모듈 추가 및 .properties 파일 추가

- .github/workflows/deploy.yml
> chore: deploy.yml 수정

- .github/workflows/deploy.yml
submodule 디렉토리 이름 변경
- [Fix] deploy.yml에서 submodule 이름 수정
-
> [Fix] deploy.yml에서 submodule 이름 수정

- src/main/java/com/strcat/StrcatApplication.java
- src/main/java/com/strcat/config/SecurityConfig.java
- src/main/java/com/strcat/config/oauth/OAuthFailureHandler.java
- src/main/java/com/strcat/config/oauth/UnauthorizedExceptionHandlerFilter.java
- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/domain/Board.java
- src/main/java/com/strcat/domain/Content.java
- src/main/java/com/strcat/domain/OAuthUser.java
- src/main/java/com/strcat/domain/User.java
- src/main/java/com/strcat/dto/ContentCreateDto.java
- src/main/java/com/strcat/dto/CreateContentReqDto.java
- src/main/java/com/strcat/exception/NotAcceptableException.java
- src/main/java/com/strcat/exception/ResponseException.java
- src/main/java/com/strcat/exception/UnauthorizedException.java
- src/main/java/com/strcat/repository/BoardRepository.java
- src/main/java/com/strcat/repository/ContentRepository.java
- src/main/java/com/strcat/repository/OAuthUserRepository.java
- src/main/java/com/strcat/repository/UserRepository.java
- src/main/java/com/strcat/service/ContentService.java
- src/main/java/com/strcat/service/OAuthUserService.java
- src/main/java/com/strcat/util/AesSecretUtils.java
- src/test/java/com/strcat/oauth/ContentServiceTest.java
- 컨텐츠 생성 로직 구현 및 테스트 완성
- AES, Cipher를 이용한 board Id 암호화 로직 구현
- 예외 발생 시 api 응답을 위한 예외 핸들링 구현 시도
- #8
> feat: 컨텐츠 생성 및 예외 처리 시도 #8

- .github/workflows/deploy.yml
> chore: ci/cd 위한 deploy 파일에 dev 추가#25

- src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/domain/Board.java
- src/main/java/com/strcat/domain/Content.java
- src/main/java/com/strcat/dto/CreateBoardReqDto.java
- src/main/java/com/strcat/dto/ReadBoardInfoResDto.java
- src/main/java/com/strcat/dto/ReadBoardSummaryResDto.java
- src/main/java/com/strcat/service/BoardService.java
- src/main/java/com/strcat/service/OAuthUserService.java
- src/main/java/com/strcat/util/AesSecretUtils.java
- src/main/java/com/strcat/util/JwtUtils.java
- src/test/java/com/strcat/oauth/ContentServiceTest.java
- 보드 구현
- JWT에 OAuthUser id에서 User id 로 변경
- AES 알고리즘 시 '/' 문자가 나오는 부분을 '_'로 변경, BASE64 참고
- #23
> feat: Implement a board

- src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
- src/main/java/com/strcat/service/BoardService.java
- src/main/java/com/strcat/util/JwtUtils.java
> refactor: PR 피드백 적용

- src/main/java/com/strcat/domain/Board.java
- src/main/java/com/strcat/dto/CreateBoardReqDto.java
- src/main/java/com/strcat/dto/ReadBoardInfoResDto.java
- src/main/java/com/strcat/service/BoardService.java
- Board entity 컬럼 이름 변경
- Board 관련 Dto의 프로퍼티 이름 변경
- Board entity 컬럼 이름 변경
- Board 관련 Dto의 프로퍼티 이름 변경
- #30
> refactor: Board entity 컬럼 수정

- src/main/java/com/strcat/config/SecurityConfig.java
- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/controller/LoginController.java
- src/main/java/com/strcat/domain/Board.java
- src/main/java/com/strcat/dto/CheckLoginResDto.java
- src/main/java/com/strcat/dto/CreateBoardReqDto.java
- src/main/java/com/strcat/dto/ReadBoardInfoResDto.java
- src/main/java/com/strcat/exception/ExceptionResolver.java
- src/main/java/com/strcat/exception/NotAcceptableException.java
- src/main/java/com/strcat/service/BoardService.java
- src/main/java/com/strcat/service/ContentService.java
- src/main/java/com/strcat/service/UserService.java
- src/main/java/com/strcat/util/AesSecretUtils.java
- src/main/java/com/strcat/util/JwtUtils.java
> Feat/implement check login#32

- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/service/BoardService.java
- import 삭제 후 커밋을 하지 않아 github action 에 실패했습니다. 한 번 더 부탁드립니다!
- #41
> Refactor/delete get board title and theme api#41

- src/main/java/com/strcat/controller/BoardGroupController.java
- src/main/java/com/strcat/domain/Board.java
- src/main/java/com/strcat/domain/BoardGroup.java
- src/main/java/com/strcat/domain/User.java
- src/main/java/com/strcat/dto/CreateBoardGroupReqDto.java
- src/main/java/com/strcat/dto/ReadBoardGroupBoardInfoResDto.java
- src/main/java/com/strcat/dto/ReadBoardGroupResDto.java
- src/main/java/com/strcat/dto/ReadBoardGroupSummaryResDto.java
- src/main/java/com/strcat/repository/BoardGroupRepository.java
- src/main/java/com/strcat/repository/BoardRepository.java
- src/main/java/com/strcat/service/BoardGroupService.java
- src/main/java/com/strcat/service/BoardService.java
- 보드 그룹 관련 기능 구현 완료했습니다...!
- 다만 클래스명, 함수명이 너무너무 길어져서 한번 봐주시고 줄이는게 좋겠다 싶으면 리팩토링하겠습니다!
- 예 : BoardGroupService내의 readBoardGroupContent 는 readContent로 줄이는 등.. 
- #36
> feat: 보드 그룹 생성, 조회, 요약 기능 구현#36

- src/test/java/com/strcat/oauth/BoardServiceTest.java
- fix: BoardService 생성자 변화를 테스트에 적용
> fix: BoardService 생성자 변화를 테스트에 적용

- build.gradle
- src/main/java/com/strcat/config/SecurityConfig.java
- src/main/java/com/strcat/config/SwaggerConfig.java
- src/main/java/com/strcat/controller/BoardController.java
> chore: Swagger 적용

- src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
- fix: redirectUrl 변경 및 쿼리 파라미터로 토큰 전달
- #63
> fix: redirectUrl 변경 및 쿼리 파라미터로 토큰 전달

- src/main/java/com/strcat/dto/ReadBoardSummaryResDto.java
- src/main/java/com/strcat/service/BoardService.java
> feat: 보드 요약 조회 api에 theme 추가 #75

- .ebextensions/build.config
- .github/workflows/deploy.yml
- .gitignore
- src/main/resources/application.properties
- 서브모듈에서 모든 properties관리를 하기 위해 기존에 origin main에 업로드된 properties 파일을 삭제하고 gitignore를 업데이트함
- 서브모듈에 application.properties(테스트용), application-prod.properties(프로덕션용)으로 파일을 나누어 생성함
- 테스트용의 경우, localhost 로 설정되어 있고 db를 매번 create하도록 함
- 프로덕션의 경우, 실제 주소로 설정되어 있고 db는 업데이트하도록 함
- 테스트를 위해 현재 aws 콘솔에서 환경변수 삭제한 상태임
- 서브모듈 파일들을 이용해 ci/cd 하기 위해 deploy.yml과 .ebextensions/build.config 수정함
- #61
> chore: 환경변수 세팅을 위한 properties 파일들, github actions, eb config 수정#61

- src/test/java/com/strcat/oauth/BoardServiceTest.java
- ReadBoardSummaryResDto 사용하는 부분 수정
- ReadBoardSummaryResDto 사용하는 부분 수정
- #81
> fix: Dto 생성자 변경에 따른 테스트 수정

- .github/workflows/deploy.yml
- src/main/resources 디렉토리 생성 명령어 추가
- 환경 재구성으로 인한 spring.datasource.url 업데이트
- #85
> fix: 깃헙 액션 수정 및 application-prod.properties db주소 업데이트#85

- src/main/java/com/strcat/controller/BoardController.java
> feat: content POST 요청 시 생성된 content id값 반환하도록 변경함

- src/main/java/com/strcat/controller/UserController.java
- src/main/java/com/strcat/dto/TmpReadMyBoardGroupInfoResDto.java
- src/main/java/com/strcat/repository/BoardGroupRepository.java
- src/main/java/com/strcat/service/BoardGroupService.java
- 암호화 id 저장이 구현되어 있지 않은 상태에서 테스트를 하기 위해 호출시 암호화하여 반환하는 방식으로 구현한 상태입니다.
- #91
> feat: 내 보드그룹 정보 조회 api 구현

- src/main/java/com/strcat/config/SecurityConfig.java
- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/controller/BoardGroupController.java
- api path에서 불필요한 부분 삭제 및 WHITE_LIST 수정
- #80
> fix: api path에서 불필요한 부분 삭제 및 WHITE_LIST 수정

- src/main/java/com/strcat/controller/UserController.java
> fix: UserController 누락된 괄호 추가함

- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/controller/BoardGroupController.java
- src/main/java/com/strcat/service/BoardGroupService.java
- src/main/java/com/strcat/service/BoardService.java
- token이 없어도 조회 가능하도록 token.isBlank() 확인 로직 추가함
- 
-
> fix: 조회 api에서 token이 없을때 에러 수정

- src/main/java/com/strcat/config/WebConfig.java
- src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
- src/test/java/com/strcat/board/BoardGroupServiceTest.java
- fix: cors주소 및 redirectURL 수정
-
> fix: cors주소 및 redirectURL 수정

- src/main/java/com/strcat/service/BoardGroupService.java
- src/main/java/com/strcat/service/BoardService.java
- src/main/java/com/strcat/service/ContentService.java
- src/main/java/com/strcat/util/SecureDataUtils.java
- src/test/java/com/strcat/board/BoardGroupServiceTest.java
- src/test/java/com/strcat/oauth/BoardServiceTest.java
- src/test/java/com/strcat/oauth/ContentServiceTest.java
- AesSecretUtils에서 SecureDataUtils로 알고리즘에 의존적이지 않도록 이름을 변경함
- #79
> refactor: AesSecretUtils에서 SecureDataUtils로 알고리즘에 의존적이지 않도록 이름을 변경함

- src/main/java/com/strcat/util/SecureDataUtils.java
> Feat/change encryption logic#108

- .github/workflows/deploy.yml
- 실수: 기존 eb에서 단일 인스턴스를 로드밸런서로 변경하였다가 다시 되돌리는 과정에서 인스턴스가 삭제됨
- 로드밸런서가 생성되면서 함께 만들어진 여러 요소들을 지울때 오토스케일링 그룹을 지운 것이 원인이지 않았을까 추측됨
- #113
> fix: eb를 재구성함에 따라 deploy.yml과 properties 수정

- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/controller/BoardGroupController.java
- src/main/java/com/strcat/domain/Board.java
- src/main/java/com/strcat/domain/BoardGroup.java
- src/main/java/com/strcat/dto/ReadBoardGroupResDto.java
- src/main/java/com/strcat/service/BoardGroupService.java
- src/main/java/com/strcat/service/BoardService.java
- src/test/java/com/strcat/board/BoardGroupServiceTest.java
> Feat/add encrypted id in response about read board and board group#112

- src/main/java/com/strcat/aop/TimeTraceAop.java
- src/main/java/com/strcat/config/SpringConfig.java
- AOP를 이용해 중요한 비즈니스 로직에 의존성이 전혀 없는 시간 측정용 메서드 구현
- 기호에 맞게 Milli, Micro, Nono 초를 측정할 수 있도록 private 함수를 구현
- SpringConfig 에 모든 필드를 초기화하는 생성자를 lombok으로 변경할 수 있어 리팩토링 함.
- #103
> feat: AOP를 통한 함수 호출 시간 측정 기능 구현

- src/main/java/com/strcat/dto/BoardResponse.java
- src/main/java/com/strcat/dto/ReadBoardResDto.java
- src/main/java/com/strcat/service/BoardService.java
- src/test/java/com/strcat/board/BoardGroupServiceTest.java
- src/test/java/com/strcat/board/BoardServiceTest.java
> fix: api 응답 변경으로 깨진 테스트 수정

- src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
> fix: redirect_uri 환경변수 호출부 수정

- src/main/java/com/strcat/service/PictureService.java
- fix: picture exception 주석처리
-
> fix: picture exception 주석처리

- src/main/java/com/strcat/config/SecurityConfig.java
- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/service/BoardService.java
- src/main/java/com/strcat/service/ShortUrlService.java
- src/test/java/com/strcat/board/BoardServiceTest.java
- fix: 토큰 없이 보드 요약 API 호출 가능하도록 변경
- fix: url 단축 api 실패시 406에러를 반환하도록 수정
-
> fix: 토큰 없이 보드 요약 API 호출 가능하도록 변경

- src/main/java/com/strcat/config/SecurityConfig.java
- fix: board 조회 API WHITE_LIST에 다시 추가
-
> fix: board 조회 API WHITE_LIST에 다시 추가

- src/main/java/com/strcat/aop/LogAop.java
- src/main/java/com/strcat/aop/TimeTraceAop.java
- src/main/java/com/strcat/config/SpringConfig.java
- src/main/java/com/strcat/repository/BoardRepository.java
- src/test/java/com/strcat/board/BoardServiceTest.java
- 컨트롤러, 서비스 호출 시 log.info() 매서드 호출로 로깅 기능 구현
- info 메서드는 배포된 애플리케이션에서 기능 실행 도중 로그를 찍을 때 보통 사용한다고 한다. log.debug() 는 기능은 같지만 개발 도중의 프로그램에서 사용한다고 한다.
- 현재 예외 사항 로깅 기능은 따로 범위를 exception 관련 범위로 따로 지정하여 구현할 예정
- DB 실행 시 초기화 설정을 update -> create 및 sql문을 프린트 하게 하는 부분을 삭제해야 한다.
- 배포할 시 데이터를 가지고 있을 예정이므로 create로 변경하면서 생기는 테스트 문제를 해결했다.
- #156
> Feat/add logging#156

- README.md
> chore: README.md 내용 추가

- src/test/java/com/strcat/board/BoardServiceTest.java
- BoardServiceTest에서 conflict를 잘못 해결하여 깨진 테스트 수정
-
> fix: BoardServiceTest에서 conflict를 잘못 해결하여 깨진 테스트 수정

- .github/workflows/deploy-dev.yml
- dev 서버 aws 계정 변경으로 인한 github flow 수정
-
> fix: dev 서버 aws 계정 변경으로 인한 github flow 수정

- src/main/java/com/strcat/repository/PictureRepository.java
- fix: prod, dev 사진 저장이 각 다른 s3에 되도록 수정
-
> fix: prod, dev 사진 저장이 각 다른 s3에 되도록 수정

- src/main/java/com/strcat/domain/Board.java
- src/main/java/com/strcat/service/BoardService.java
- Board에서 처리할 수 있는 dto관련 메서드들을 BoardService에서 Board로 이동함
- fetchBoardResponse대신 Board내 toBoardResponse 와 toReadBoardResDto로 대체
- ReadBoardResDto,
- ReadBoardSummaryResDto,
- ReadMyInfoResDto 의 경우도 동일하게 Board에서 처리함
- #161
> refactor: Board에서 처리할 수 있는 dto관련 메서드들을 BoardService에서 Board로 이동함

- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/controller/LoginController.java
- src/main/java/com/strcat/controller/UserController.java
- fix: swagger status code가 실제와 일치하지 않던 부분 수정
- #168
> fix: swagger status code가 실제와 일치하지 않던 부분 수정

- src/main/java/com/strcat/controller/BoardController.java
- src/main/java/com/strcat/service/ContentService.java
- src/test/java/com/strcat/board/ContentServiceTest.java
- refactor: BoardService의 create--- 메서드의 반환타입 일치
- #167
> refactor: BoardService의 create--- 메서드의 반환타입 일치#167

- src/test/java/com/strcat/board/ContentServiceTest.java
deleteContent 메서드 반환값을 리팩터링하고 테스트에서 수정하지 않은 부분 수정
- ContentServiceTest 수정
-
> fix: ContentServiceTest 수정

- src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
> feat: 쿠키에 토큰 추가

- src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
> feat: 쿠키 관련 보안 설정 추가

- src/main/java/com/strcat/config/oauth/OAuthSuccessHandler.java
> feat: 쿠키 설정 변경
